// Generated by CoffeeScript 1.8.0
(function() {
  var match,
    __slice = [].slice;

  module.exports = match = function() {
    var args, i, k, keys, n, pairs, target, v, vals, _i, _name;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    if (args.length > 2) {
      target = args[0], pairs = 2 <= args.length ? __slice.call(args, 1) : [];
    } else {
      target = args[0], pairs = args[1];
    }
    keys = pairs.filter(function(n, i) {
      return !(i % 2);
    });
    vals = pairs.filter(function(n, i) {
      return i % 2;
    });
    n = vals.length;
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      k = keys != null ? keys[i] : void 0;
      v = vals != null ? vals[i] : void 0;
      if ((typeof k) === 'string' && k === target) {
        return v();
      } else if ((k != null ? k.name : void 0) && (target instanceof k)) {
        return v();
      } else if ((k instanceof Function) && (typeof k === "function" ? k(target) : void 0)) {
        return v();
      } else {
        if (k === target) {
          return v();
        }
      }
    }
    if (keys.length !== vals.length) {
      return typeof keys[_name = keys.length - 1] === "function" ? keys[_name]() : void 0;
    }
    return void 0;
  };

}).call(this);
