// Generated by CoffeeScript 1.8.0
(function() {
  var match;

  module.exports = match = function(target, pairs) {
    var i, k, keys, n, v, vals, _i, _name;
    if (arguments.length > 2) {
      pairs = arguments.slice(1);
    }
    keys = pairs.filter(function(n, i) {
      return !(i % 2);
    });
    vals = pairs.filter(function(n, i) {
      return i % 2;
    });
    n = vals.length;
    for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
      k = keys[i];
      v = vals[i];
      if ((typeof k) === 'string' && k === target) {
        return v();
      } else if ((k != null ? k.name : void 0) && (target instanceof k)) {
        return v();
      } else if ((k instanceof Function) && (typeof k === "function" ? k(target) : void 0)) {
        return v();
      }
    }
    if (keys.length !== vals.length) {
      return typeof keys[_name = keys.length - 1] === "function" ? keys[_name]() : void 0;
    }
    return void 0;
  };

}).call(this);
